export enum IframeEventsEnum {
    AUTH_TOKEN_RESPONSE = 'AUTH_TOKEN_RESPONSE',
    AUTH_TOKEN_MISSING = 'AUTH_TOKEN_MISSING',
    AUTH_TOKEN_DELETED = 'AUTH_TOKEN_DELETED',
    AUTH_TOKEN_DELETE_ERROR = 'AUTH_TOKEN_DELETE_ERROR',
    AUTH_TOKEN_STORE_ERROR = 'AUTH_TOKEN_STORE_ERROR',
    AUTH_TOKEN_STORED = 'AUTH_TOKEN_STORED',
}
